name: On Release Created (Publish cherrypick-js)

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package
        run: |
          corepack enable
          pnpm i --frozen-lockfile
          pnpm build
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
